inherit_from:
  - ~/rubocop/default.yml # Embedded inside Docker

AllCops:
  Exclude:
    - 'PodBinaryCacheExample/**/*'
    - 'lib/cocoapods-binary-cache/pod-binary/**/*'
    - 'lib/cocoapods-binary-cache/pod-rome/**/*'
