name: lint
on:
  pull_request:
    branches:
      - master
jobs:
  danger:
    runs-on: ubuntu-latest
    env:
      DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Ruby setup
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Bundle installation
        run: |
          gem install bundler:2.1.2
          bundle install
      - name: Rubocop
        run: |
          bundle exec danger || true
        # TODO (thuyen): Comments (with GITHUB_TOKEN) are not working with fork-based MRs
